name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: true
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build Production Images and Push - Server
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ga63qes/image-weather-recognition:latest
            ga63qes/image-weather-recognition:${{ github.sha }}